### ISSUE TITLE
User: first_name, last_name, user_name strings not rendering in views

### ISSUE THREAD

**Issue by austin-thesing** [austin-thesing/blocpedia#4]
I added new fields to users and when I try to call them in views they do not show up.. But the original email field is still visible and works properly.

**Comment by cbeck** [comment]
You missed the step of configuring the santized parameters for devise. It locks down what you can pass in from your forms for security. 

Check out this article: http://stackoverflow.com/questions/19791531/how-to-specify-devise-parameter-sanitizer-for-edit-action

 Don't overthink this checkpoint - there really wasn't much to do here because you won't actually be doing much with Pundit until checkpoints 7, 8 and 10. Until then, they just wanted it installed and wanted to show you how to make a change to a policy.

**Comment by austin-thesing** [comment]
Followed article's advice and configured parameter sanitizer for the new parameters
